Don improved HelpWindow UI
AY2021S2-CS2103-T14-2/tp pull request #83
Opened 2021-03-24 15:39 UTC by Donavanty

Improved the HelpWindow UI

2021-03-28 16:41 UTC, Donavanty commented
I accidentally merged Marcus' work-in-progress, which is causing checkstyleTest test to fail, but I can't resolve it yet

2021-03-28 17:39 UTC, Prabhakaran-Gokul requested changes

2021-03-28 17:39 UTC, Prabhakaran-Gokul commented on src/main/java/fooddiary/ui/HelpWindow.java
> +                    + "add: Adds a food review to the Food Diary.\n"
Should it be 'entry' instead of 'food review'?

2021-03-28 18:08 UTC, Donavanty commented on src/main/java/fooddiary/ui/HelpWindow.java
> +                    + "add: Adds a food review to the Food Diary.\n"
Will change to 'entry', thanks :)

2021-03-29 01:13 UTC, marcusleeeugene approved these changes

2021-03-29 01:13 UTC, marcusleeeugene commented on docs/UserGuide.md
> +**Add** | `add n/<RESTAURANT NAME> ra/<RATING FROM 1-5> re/<REVIEW> a/<ADDRESS> c/<CATEGORIES>` <br> e.g., `add  n/Al Amaan Restaurant ra/4 re/best for Butter Chicken a/12 Clementi Rd, Singapore 1297
Rating is from 0-5

2021-03-29 01:13 UTC, marcusleeeugene commented on src/main/java/fooddiary/logic/commands/ViewCommand.java
> +        return new CommandResult(entry, String.format(MESSAGE_VIEW_ENTRY_SUCCESS, entry),
Not sure if your revert worked correctly, because my implementation was initially HashMap. I'll merge in yours probably the last since it already takes in my new changes.

2021-03-29 04:36 UTC, Sidney011100 commented on src/main/resources/view/ViewWindow.fxml
>  <fx:root resizable="false" title="Viewing Specified Entry" type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1">
java version should be less than or equal to 11

2021-03-29 04:36 UTC, Donavanty commented on src/main/resources/view/MainWindow.fxml
> +        <StackPane fx:id="resultDisplayPlaceholder" maxHeight="130.0" minHeight="130.0" prefHeight="130.0" styleClass="pane-with-border" VBox.vgrow="NEVER">
This is now 130, to accommodate for 4 lines of comments shown without scrolling

2021-03-29 04:38 UTC, Donavanty commented on src/main/resources/view/HelpWindow.fxml
> +               <TextArea fx:id="helpMessageField" editable="false" scaleShape="false" style="-fx-control-inner-background: derive(#1d1d1d, 30%); -fx-text-fill: white; -fx-border-color: transparent; -
I did styling individually instead of using DarkTheme.css, might have to change in the future if colour scheme changes

2021-03-29 04:39 UTC, Donavanty commented on src/main/java/fooddiary/ui/HelpWindow.java
> +                    + "PGP, USC, CLB, UHALL, SDE, MED, DENT, VENTUS, INVALID\n\n\n";
Added Food Categories and School Locations enumeration types in the Help guide, to allow users to see what types they can use

2021-03-29 04:39 UTC, Sidney011100 reviewed
nice, thanks don

2021-03-29 04:39 UTC, Donavanty commented on src/main/java/fooddiary/logic/commands/ViewCommand.java
> +        return new CommandResult(entry, String.format(MESSAGE_VIEW_ENTRY_SUCCESS, entry),
Thanks Marcus, yeah probably merged wrongly

2021-03-29 04:40 UTC, Donavanty commented on src/main/resources/view/ViewWindow.fxml
>  <fx:root resizable="false" title="Viewing Specified Entry" type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1">
Okay, will edit and push again, thanks Sid

2021-03-29 17:01 UTC, Prabhakaran-Gokul approved these changes
LGTM!

2021-03-30 18:34 UTC, merged